clc;clear;close all;
% 高程
contourMap('D:/01B硕士/CAD二次开发/data/data_max.xlsx',...
    'D:/01B硕士/CAD二次开发/data/contourM.xlsx',-5,50,1,1);
% 等水压线
contourMap('D:/01B硕士/CAD二次开发/data/data_max.xlsx',...
    'D:/01B硕士/CAD二次开发/data/contourM.xlsx',15,60,2,0);
contourMap('D:/01B硕士/CAD二次开发/data/data_fire.xlsx',...
    'D:/01B硕士/CAD二次开发/data/contourM.xlsx',15,60,3,0);
contourMap('D:/01B硕士/CAD二次开发/data/data_acc.xlsx',...
    'D:/01B硕士/CAD二次开发/data/contourM.xlsx',15,60,4,0);